### ISSUE TITLE
error when "python scripts/example.py"

### ISSUE THREAD

**Issue by likelyw** [allenai/procthor#49]
@Lucaweihs 
Traceback (most recent call last):
  File "scripts/example.py", line 6, in <module>
    house, _ = house_generator.sample()
  File "/home/haha/桌面/procthor-main/procthor/generation/__init__.py", line 131, in sample
    self.controller = Controller(quality="Low", **PROCTHOR_INITIALIZATION)
  File "/home/haha/anaconda3/envs/procthor/lib/python3.8/site-packages/ai2thor/controller.py", line 513, in __init__
    self._build = self.find_build(local_build, commit_id, branch, platform)
  File "/home/haha/anaconda3/envs/procthor/lib/python3.8/site-packages/ai2thor/controller.py", line 1306, in find_build
    raise ValueError(
ValueError: Invalid commit_id: f0825767cd50d69f666c7f282e54abfe58f1e917 - no build exists for arch=Linux platforms=Linux64
 can you please tell me how to solve this?

**Comment by bowieshi** [comment]
I met the same problem. Do you find a way to solve it?

> @Lucaweihs Traceback (most recent call last): File "scripts/example.py", line 6, in house, _ = house_generator.sample() File "/home/haha/桌面/procthor-main/procthor/generation/**init**.py", line 131, in sample self.controller = Controller(quality="Low", **PROCTHOR_INITIALIZATION) File "/home/haha/anaconda3/envs/procthor/lib/python3.8/site-packages/ai2thor/controller.py", line 513, in **init** self._build = self.find_build(local_build, commit_id, branch, platform) File "/home/haha/anaconda3/envs/procthor/lib/python3.8/site-packages/ai2thor/controller.py", line 1306, in find_build raise ValueError( ValueError: Invalid commit_id: f0825767cd50d69f666c7f282e54abfe58f1e917 - no build exists for arch=Linux platforms=Linux64 can you please tell me how to solve this?

**Comment by usernameforu** [comment]
@bowieshi Me too!Have you found a solution?

**Comment by giao-123-sun** [comment]
I find the problem be solved when I changed the version of ai2thor from 5.0.0 to 4.0.0.
It might be  a problem for version conflict I think.
Citation and thanks for :"https://github.com/allenai/ai2thor-rearrangement/issues/25"

**Comment by LearningLeopard** [comment]
Hey @giao-123-sun , I have already installed the 4.0.0 version but the issue still seems to exist. Also I have not installed via pip but I built it from source because doing it via pip install was a dead end too. Were you able to solve this?

**Comment by SRastegari** [comment]
Hi @LearningLeopard, could you solve the problem? I tried version 4.0.0 too, but it didn't help.

**Comment by chang-xinhai** [comment]
Any update? Same problem, and 4.0.0 is not helpful too.

**Comment by ruiqixu37** [comment]
I met the same issue and fixed it by further downgrading `ai2thor` to `3.5.0`. I am on Ubuntu 22.04.
