### ISSUE TITLE
error when running example.py Unable to CreateHouse!

### ISSUE THREAD

**Issue by 1170300716X** [allenai/procthor#52]
When I tried to run example.py, there were two differernt errors. Could you please tell me what should I do?
The version of ai2thor is 4.0.0, and procthor is 0.0.1.dev2. I have tried to change the version of them, but it didn't work.
$ python scripts/example.py
Traceback (most recent call last):
  File "scripts/example.py", line 6, in <module>
    house, _ = house_generator.sample()
  File "/home/madxx/anaconda3/envs/ai2thor_env/lib/python3.8/site-packages/procthor/generation/__init__.py", line 195, in sample
    add_wall_objects(
  File "/home/madxx/anaconda3/envs/ai2thor_env/lib/python3.8/site-packages/procthor/generation/wall_objects.py", line 1018, in add_wall_objects
    add_windows(
  File "/home/madxx/anaconda3/envs/ai2thor_env/lib/python3.8/site-packages/procthor/generation/wall_objects.py", line 337, in add_windows
    rooms_lines_df_map = get_line_string_df_map(
  File "/home/madxx/anaconda3/envs/ai2thor_env/lib/python3.8/site-packages/procthor/generation/wall_objects.py", line 285, in get_line_string_df_map
    bounds = line_string.boundary.geoms
AttributeError: 'NoneType' object has no attribute 'geoms'
 
python scripts/example.py
Traceback (most recent call last):
  File "scripts/example.py", line 6, in <module>
    house, _ = house_generator.sample()
  File "/home/madxx/anaconda3/envs/ai2thor_env/lib/python3.8/site-packages/procthor/generation/__init__.py", line 209, in sample
    add_small_objects(
  File "/home/madxx/anaconda3/envs/ai2thor_env/lib/python3.8/site-packages/procthor/generation/small_objects.py", line 85, in add_small_objects
    assert event, "Unable to CreateHouse!"
AssertionError: Unable to CreateHouse!

**Comment by nemo622116** [comment]
Hi have you solved the second problem？
